version: '3.7'

services:

  api:
    build:
      context: ./services/web
    command: python manage.py run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: estore
      POSTGRES_HOST_AUTH_METHOD: trust
      SQLALCHEMY_TRACK_MODIFICATIONS: 0

volumes:
  db_data:
